application: real-time-chat
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /font
  static_dir: font
- url: /bootstrap
  static_dir: bootstrap
- url: /js
  static_dir: js
- url: /.*
  script: rtchat.application

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
